### ISSUE TITLE
Fuji crashing server

### ISSUE THREAD

**Issue by payphone101** [fuji-fabric/fuji#146] opened 2024-10-06 08:15 UTC
How to Reproduce the bug?
1. Install Fuji 1.5.9 and update it to 1.6.0
2. Update it to 1.6.3 or later
3. ???
4. Server crash with error on first mclogs link below

What is the expected behavior?

Should have updated no problem since it didn't crash on 1.6.0 -> 1.6.2

What is the actual behavior?

server crashing

Please upload the server logs using https://mclo.gs/
Yes, my logs link is: 
Error log: https://mclo.gs/GbXp8kk
Server Latest Log: https://mclo.gs/nDhxXWF

**Comment by sakurawald** [comment] 2024-10-06 08:19
Hello, please install the latest version fuji 1.7.0.
And upload the `config/fuji/config.josn` file.

**Comment by sakurawald** [comment] 2024-10-06 08:22
It seems like a problem of `command permission module`, You can try disable this module, and see if this crash exists

**Comment by sakurawald** [comment] 2024-10-06 08:34
The reason is that, one of the mods trigger the `CommandNode#getRequirement` too early, which causing the `command_permission module` failed to inject the permission predicate wrapper.

I have update the `fuji v1.7.1` version , which should fix this.

Thank you for your feedback!

**Comment by payphone101** [comment] 2024-10-06 09:24
is it the same reason why the console is being spammed with this?
`[09:20:46] [Server thread/ERROR] CommandExecuter fails to execute commands.`

**Comment by sakurawald** [comment] 2024-10-06 09:39
> is it the same reason why the console is being spammed with this? `[09:20:46] [Server thread/ERROR] CommandExecuter fails to execute commands.`

No, this warning comes from a command executed by `meta commands` or `command scheduler` or something like that, it's possible that there is a `command syntax error` while executing these commands.

The error feedback is highly enhanced in `fuji v1.7.1`, so that you can see clear what exactly the error command is. So I just recommend you to use the newer version if possible.

Clearer, fuji improves the `command executor` and its exception reporter in `fuji v1.6.8` version, so the feedback will be more useful and less confused.

**Comment by sakurawald** [comment] 2024-10-06 12:42
> is it the same reason why the console is being spammed with this? `[09:20:46] [Server thread/ERROR] CommandExecuter fails to execute commands.`

I have check this, it's like this comes from `command_scheduler module`, if you are not using this module, you can just disable it.
Or you can edit the config file `config/fuji/modules/command_scheduler/scheduler.json` and delete the `broken entry`, and issue `/fuji reload`

After that, the console spam will be fixed.

**Comment by payphone101** [comment] 2024-10-06 13:05
Still getting the same error with 1.7.1
```06.10 13:04:40 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3734()" because the return value of "io.github.sakurawald.core.auxiliary.minecraft.ServerHelper.getDefaultServer()" is null
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
06.10 13:04:40 [Server] INFO at net.minecraft.server.Main.main(Main.java:229) [server-intermediary.jar:?]
06.10 13:04:40 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.5.jar:?]
06.10 13:04:40 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.5.jar:?]
06.10 13:04:40 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.5.jar:?]
06.10 13:04:40 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.5.jar:?]
06.10 13:04:40 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3734()" because the return value of "io.github.sakurawald.core.auxiliary.minecraft.ServerHelper.getDefaultServer()" is null
06.10 13:04:40 [Server] INFO at io.github.sakurawald.core.auxiliary.minecraft.ServerHelper.getCommandDispatcher(ServerHelper.java:32) ~[fuji-1.7.0-release-20c0880a96.jar:?]
06.10 13:04:40 [Server] INFO at com.mojang.brigadier.tree.CommandNode.modifyReturnValue$bgn000$fuji$injected(CommandNode.java:536) ~[brigadier-1.3.10.jar:?]
06.10 13:04:40 [Server] INFO at com.mojang.brigadier.tree.CommandNode.getRequirement(CommandNode.java:138) ~[brigadier-1.3.10.jar:?]
06.10 13:04:40 [Server] INFO at org.incendo.cloud.brigadier.util.BrigadierUtil.buildRedirect(BrigadierUtil.java:60) ~[org_incendo_cloud-brigadier-2.0.0-beta.8-2013d081b8e00658.jar:?]
06.10 13:04:40 [Server] INFO at org.incendo.cloud.fabric.FabricCommandRegistrationHandler$Server.registerCommand(FabricCommandRegistrationHandler.java:204) ~[cloud-2.0.0-beta.7-ee6d1d45e867138d.jar:?]
06.10 13:04:40 [Server] INFO at org.incendo.cloud.fabric.FabricCommandRegistrationHandler$Server.lambda$registerAllCommands$0(FabricCommandRegistrationHandler.java:184) ~[cloud-2.0.0-beta.7-ee6d1d45e867138d.jar:?]
06.10 13:04:40 [Server] INFO at org.incendo.cloud.minecraft.modded.internal.ContextualArgumentTypeProvider.withBuildContext(ContextualArgumentTypeProvider.java:74) ~[org_incendo_cloud-minecraft-modd.0.0-beta.7-30cb687f1ffdf91d.jar:?]
06.10 13:04:40 [Server] INFO at org.incendo.cloud.fabric.FabricCommandRegistrationHandler$Server.registerAllCommands(FabricCommandRegistrationHandler.java:168) ~[cloud-2.0.0-beta.7-ee6d1d45e867138d.jar:?]
06.10 13:04:40 [Server] INFO at net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback.lambda$static$0(CommandRegistrationCallback.java:43) ~[fabric-command-api-v2-2.2.28+6ced4dd919-67461be3fde1e6dc.jar:?]
06.10 13:04:40 [Server] INFO at net.minecraft.class_2170.handler$znm000$fabric-command-api-v2$fabric_addCommands(class_2170.java:2617) ~[server-intermediary.jar:?]
06.10 13:04:40 [Server] INFO at net.minecraft.class_2170.<init>(class_2170.java:288) ~[server-intermediary.jar:?]
06.10 13:04:40 [Server] INFO at net.minecraft.class_5350.<init>(class_5350.java:52) ~[server-intermediary.jar:?]
06.10 13:04:40 [Server] INFO at net.minecraft.class_5350.method_58296(class_5350.java:83) ~[server-intermediary.jar:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
06.10 13:04:40 [Server] INFO at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]```

**Comment by sakurawald** [comment] 2024-10-06 13:23
> fuji-1.7.0-r

Hey, the version is wrong. Please download `fuji v1.7.1` instead of `fuji v1.7.0`

**Comment by payphone101** [comment] 2024-10-06 14:25
hmm, I swear I uploaded 1.7.1... will retry and report back

**Comment by sakurawald** [comment] 2024-10-06 22:08
> hmm, I swear I uploaded 1.7.1... will retry and report back

The `fuji v1.7.1` version can be downloaded in https://modrinth.com/mod/fuji/version/1.7.1-release-9a0bcd88df

The error message in the log indicates that this is a `1.7.0` version
```
06.10 13:04:40 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3734()" because the return value of "io.github.sakurawald.core.auxiliary.minecraft.ServerHelper.getDefaultServer()" is null
06.10 13:04:40 [Server] INFO at io.github.sakurawald.core.auxiliary.minecraft.ServerHelper.getCommandDispatcher(ServerHelper.java:32) ~[fuji-1.7.0-release-20c0880a96.jar:?]
```

**Comment by payphone101** [comment] 2024-10-07 16:17
cool, it works now for the most part, just the `brigadier` error console spam is happening, usually pointing to either 0 (which I guess is the console) or the player currently online

**Comment by sakurawald** [comment] 2024-10-07 23:59
> cool, it works now for the most part, just the `brigadier` error console spam is happening, usually pointing to either 0 (which I guess is the console) or the player currently online

If you see the error message periodically, then it's possible the error message is caused by `command_scheduler module`.

This module provides function to execute commands as console periodically. Maybe there is some `command syntax error` in the configuration file of command scheduler module, so each time the scheduler submit these commands to the `brigadier` system, the system complains about it.

You can disable the scheduler task by: open the `config/fuji/modules/command_scheduler/scheduler.json`, and modify the `"enable": true` into `"enable":false`, and issue `/fuji reload`.

**Comment by payphone101** [comment] 2024-10-12 02:31
config folder doesn't contain the `command_scheduler` module
![image](https://github.com/user-attachments/assets/68533586-01e2-4135-a50b-452eaba01dbe)

**Comment by sakurawald** [comment] 2024-10-12 05:59
> config folder doesn't contain the `command_scheduler` module ![image](https://private-user-images.githubusercontent.com/89388404/375917479-68533586-01e2-4135-a50b-452eaba01dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTI3MTYsIm5iZiI6MTcyODcxMjQxNiwicGF0aCI6Ii84OTM4ODQwNC8zNzU5MTc0NzktNjg1MzM1ODYtMDFlMi00MTM1LWE1MGItNDUyZWFiYTAxZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA1NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNGJiODEzY2NlYjYzMjI0YjkwYzYzZTllZDU5YTEwNDVlYjk5MjdmYjhkZjAwNjUxZGVhZjc1MWZmYjMxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lXdBcC7UKbmH2zDSJHYqZKAdZP3Kooc6XVohvpeRZ38)

Now we confirm that this `console spam` is not come from the `command scheduler module`.
So let's check the `afk module`, to see what commands are written in the `afk_event` in file `config/fuji/modules/afk/config.json`. 

We should remove the `broken command syntax` inside the `afk_event`, so that when these commands is submitted to the `brigadier command system`, they are correct and can be parsed and executed.

**Comment by payphone101** [comment] 2024-10-13 17:06
[config.json](https://github.com/user-attachments/files/17356413/config.json)
This is what I have, it's never been altered

**Comment by sakurawald** [comment] 2024-10-13 18:31
> > config folder doesn't contain the `command_scheduler` module ![image](https://private-user-images.githubusercontent.com/89388404/375917479-68533586-01e2-4135-a50b-452eaba01dbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTI3MTYsIm5iZiI6MTcyODcxMjQxNiwicGF0aCI6Ii84OTM4ODQwNC8zNzU5MTc0NzktNjg1MzM1ODYtMDFlMi00MTM1LWE1MGItNDUyZWFiYTAxZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA1NTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhNGJiODEzY2NlYjYzMjI0YjkwYzYzZTllZDU5YTEwNDVlYjk5MjdmYjhkZjAwNjUxZGVhZjc1MWZmYjMxYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lXdBcC7UKbmH2zDSJHYqZKAdZP3Kooc6XVohvpeRZ38)
> 
> Now we confirm that this `console spam` is not come from the `command scheduler module`. So let's check the `afk module`, to see what commands are written in the `afk_event` in file `config/fuji/modules/afk/config.json`.
> 
> We should remove the `broken command syntax` inside the `afk_event`, so that when these commands is submitted to the `brigadier command system`, they are correct and can be parsed and executed.

Yeah, the command `/send-broadcast` is provided by `echo.send_broadcast module`.
If this module is disabled, then this command will not exist, so this will cause a `command syntax error` while trying to executing this command.

You can enable this module, or modify the usage of `/send-broadcast` into the vanilla alternative `/say`

**Comment by payphone101** [comment] 2024-10-14 11:58
I'm assuming you mean the `echo` module in the main config `/config/fuji/config.json`, which I checked and saw that it was disabled this whole time...
![image](https://github.com/user-attachments/assets/aca1bcc3-f1d3-453b-af9f-1da8e2f35ea0)

**Comment by payphone101** [comment] 2024-10-14 13:43
also server doesn't seem to recognise `/fuji reload`
![image](https://github.com/user-attachments/assets/780f90c6-e226-4f11-949b-5d6ae50df81b)

**Comment by sakurawald** [comment] 2024-10-14 13:45
> also server doesn't seem to recognise `/fuji reload` ![image](https://private-user-images.githubusercontent.com/89388404/376264208-780f90c6-e226-4f11-949b-5d6ae50df81b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MTM4MDIsIm5iZiI6MTcyODkxMzUwMiwicGF0aCI6Ii84OTM4ODQwNC8zNzYyNjQyMDgtNzgwZjkwYzYtZTIyNi00ZjExLTk0OWItNWQ2YWU1MGRmODFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEzNDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMmQxMThkZGVjNzVhOGE2Nzg5YWZhNjE5YmMyNjVlMmE0M2JlZjExZTRmNmIxMDM4MmJlMmZjMWE1YWU5MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ohIE6gWpe33CAM-WIiivHyAGVZs7CQhZc7xYhhilV0s)

The `/fuji reload` is provided by `fuji module`.
Also, the command `/fuji reload` only reloads the configuration for a enabled module.
After you enable/disable a module, the server must restart to apply the changes.

**Closed as completed** 2024-10-15 17:57 UTC
Labels: bug
