### ISSUE TITLE
[feature] Add customization to teleport_warmup

### ISSUE THREAD

**Issue by FishyFinn** [fuji-fabric/fuji#227] opened 2024-12-23 13:33 UTC
### Is there an existing request for feature?

- [X] I have searched the existing issues

### What feature would you like?

Customizability around the teleport_warmup module
either permission meta on role specific warm ups: EG admins have instant teleports 
command white/ blacklists: commands like /warp are quicker than /back, or /tp is instant as its an operator command 

I think either of these would be great features that would enable easier moderating

**Comment by sakurawald** [comment] 2024-12-23 13:40
It's possible to add a `warmup bypass permission` for admin, and `different warmup time` for different `permission`.
But it's im-possible to distinguish the cause of this teleport, e.g. you don't know which command starts this teleport, and the teleport can also be started via other mods directly in the internal game logic.

You can try `command-warmup module` to setup a warmup for different commands, like `back` and `warp`.

I have no time until 2025 middle, this request will be handleed after that.

**Comment by FishyFinn** [comment] 2024-12-24 09:36
Thanks!

I'm using this as an opportunity to learn git so i can contribute myself. But I've run into a bug that i hadn't before.

When teleport_warmup is enabled 'relative' position teleports don't work. eg `/tp ~ ~ ~` will just teleport the player to 0 0 0 or `/tp ~ ~10 ~` will teleport you to 0 10 0. I've confirmed this on the most recent 1.21.4 version with and without teleport_warmup enabled. 

I'll open another issue for this and create a PR for this feature

**Comment by sakurawald** [comment] 2024-12-24 10:46
> Thanks!
> 
> I'm using this as an opportunity to learn git so i can contribute myself. But I've run into a bug that i hadn't before.
> 
> When teleport_warmup is enabled 'relative' position teleports don't work. eg `/tp ~ ~ ~` will just teleport the player to 0 0 0 or `/tp ~ ~10 ~` will teleport you to 0 10 0. I've confirmed this on the most recent 1.21.4 version with and without teleport_warmup enabled.
> 
> I'll open another issue for this and create a PR for this feature

Mojang re-factor the `teleport` function in recent version, and they introduce a `position flags` to identify the `absolute teleport` and `relative teleport`. If you are interesting to make a pr for this, you can look into it.
The related source is at: https://github.com/sakurawald/fuji/blob/dev/src/main/java/io/github/sakurawald/module/mixin/teleport_warmup/ServerPlayerMixin.java

And the `position flag`: https://github.com/sakurawald/fuji/blob/dev/src/main/java/io/github/sakurawald/core/structure/SpatialPose.java
Thank you!

**Comment by sakurawald** [comment] 2024-12-25 01:12
> Thanks!
> 
> I'm using this as an opportunity to learn git so i can contribute myself. But I've run into a bug that i hadn't before.
> 
> When teleport_warmup is enabled 'relative' position teleports don't work. eg `/tp ~ ~ ~` will just teleport the player to 0 0 0 or `/tp ~ ~10 ~` will teleport you to 0 10 0. I've confirmed this on the most recent 1.21.4 version with and without teleport_warmup enabled.
> 
> I'll open another issue for this and create a PR for this feature

Thank you! I have make the review on the pr, all looks good, but it's better to use the overload of function, to reduce the dupe of code. Yeah, I would like to keep the codes as simple as possible, making it easier to understand.

**Closed as completed by sakurawald** 2024-12-25 01:12 UTC
Labels: enhancement, help wanted, good first issue
